name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: codfish/semantic-release-action@master
      id: version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag advancedcsg/action-jfrog-cli:latest
    - name: Publish
      if: steps.version.outputs.new-release-published == 'true'
      uses: manusa/actions-publish-docker@master
      with:
        name: advancedcsg/action-jfrog-cli
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        tag: ${{ steps.version.outputs.release-version }}
